import { SiteData } from './types';

export const defaultData: SiteData = {
  news: [
    {
      id: '1',
      titleKo: 'SHAPE 동아리 2024년 신입 부원 모집',
      titleEn: 'SHAPE Club 2024 New Member Recruitment',
      contentKo:
        'SNU Humanoid Club SHAPE에서 2024년도 신입 부원을 모집합니다. 로봇공학에 관심 있는 학생이라면 누구든 환영합니다. 조작, 내비게이션, 추론, 인지 등 다양한 분야에서 함께 연구하고 성장할 기회를 드립니다.',
      contentEn:
        'SNU Humanoid Club SHAPE is recruiting new members for 2024. We welcome all students interested in robotics. Join us to research and grow in various fields including manipulation, navigation, reasoning, and perception.',
      date: '2024-03-01',
      category: 'Recruitment',
      imageUrl: '',
    },
    {
      id: '2',
      titleKo: 'ICRA 2024 논문 발표 성공',
      titleEn: 'Successful Paper Presentation at ICRA 2024',
      contentKo:
        'SHAPE 연구팀이 국제로봇공학자동화학회(ICRA 2024)에서 휴머노이드 로봇의 동적 조작 제어에 관한 논문을 성공적으로 발표하였습니다.',
      contentEn:
        'The SHAPE research team successfully presented a paper on dynamic manipulation control of humanoid robots at the International Conference on Robotics and Automation (ICRA 2024).',
      date: '2024-05-15',
      category: 'Research',
      imageUrl: '',
    },
    {
      id: '3',
      titleKo: '전국 로봇 경진대회 우수상 수상',
      titleEn: 'Excellence Award at National Robot Competition',
      contentKo:
        'SHAPE 팀이 2024년 전국 로봇 경진대회에서 휴머노이드 부문 우수상을 수상하였습니다. 팀원 모두의 노력과 헌신이 이룬 결실입니다.',
      contentEn:
        'The SHAPE team won the Excellence Award in the humanoid division at the 2024 National Robot Competition. This is the result of the effort and dedication of all team members.',
      date: '2024-11-20',
      category: 'Award',
      imageUrl: '',
    },
  ],
  history: [
    {
      id: '1',
      year: 2020,
      month: 3,
      titleKo: 'SHAPE 동아리 창설',
      titleEn: 'SHAPE Club Founded',
      descriptionKo:
        '서울대학교 자율로봇 지능 연구실과 협력하여 SNU Humanoid Club SHAPE가 공식 창설되었습니다.',
      descriptionEn:
        'SNU Humanoid Club SHAPE was officially founded in collaboration with the SNU Autonomous Robot Intelligence Lab.',
    },
    {
      id: '2',
      year: 2021,
      month: 6,
      titleKo: '첫 번째 휴머노이드 플랫폼 도입',
      titleEn: 'First Humanoid Platform Introduced',
      descriptionKo:
        '동아리 최초의 휴머노이드 로봇 플랫폼을 도입하여 본격적인 연구 활동을 시작하였습니다.',
      descriptionEn:
        'The club introduced its first humanoid robot platform, beginning full-scale research activities.',
    },
    {
      id: '3',
      year: 2022,
      month: 9,
      titleKo: '국내 로봇 경진대회 첫 참가',
      titleEn: 'First Participation in National Robot Competition',
      descriptionKo:
        '전국 로봇 경진대회에 처음 참가하여 기술력을 선보이고 다른 팀들과 교류하였습니다.',
      descriptionEn:
        'Participated in a national robot competition for the first time, showcasing technical skills and networking with other teams.',
    },
    {
      id: '4',
      year: 2023,
      month: 5,
      titleKo: 'ICRA 논문 첫 게재',
      titleEn: 'First ICRA Paper Publication',
      descriptionKo:
        'ICRA에 첫 번째 논문을 게재하며 국제 학술 무대에 이름을 알리기 시작하였습니다.',
      descriptionEn:
        'Published the first paper at ICRA, beginning to make a name for ourselves on the international academic stage.',
    },
    {
      id: '5',
      year: 2024,
      month: 11,
      titleKo: '전국 대회 우수상 수상',
      titleEn: 'Excellence Award at National Competition',
      descriptionKo:
        '전국 로봇 경진대회 휴머노이드 부문에서 우수상을 수상하며 기술력을 인정받았습니다.',
      descriptionEn:
        'Won the Excellence Award in the humanoid division at the National Robot Competition, receiving recognition for technical excellence.',
    },
  ],
  gallery: [
    {
      id: '1',
      titleKo: '2024 로봇 경진대회',
      titleEn: '2024 Robot Competition',
      descriptionKo: '전국 로봇 경진대회 현장에서의 팀원들의 모습',
      descriptionEn: 'Team members at the National Robot Competition',
      imageUrl: '',
      date: '2024-11-20',
    },
    {
      id: '2',
      titleKo: '연구실 세미나',
      titleEn: 'Lab Seminar',
      descriptionKo: '자율로봇 지능 연구실에서 진행된 정기 세미나',
      descriptionEn: 'Regular seminar held at the Autonomous Robot Intelligence Lab',
      imageUrl: '',
      date: '2024-09-10',
    },
    {
      id: '3',
      titleKo: '휴머노이드 시연',
      titleEn: 'Humanoid Demonstration',
      descriptionKo: '교내 과학기술제에서 휴머노이드 로봇을 시연하는 모습',
      descriptionEn: 'Demonstrating the humanoid robot at the campus science festival',
      imageUrl: '',
      date: '2024-06-05',
    },
  ],
  members: [
    {
      id: '1',
      nameKo: '홍길동',
      nameEn: 'Kildong Hong',
      role: 'director',
      titleKo: '지도교수',
      titleEn: 'Director / Professor',
      affiliationKo: '서울대학교 기계공학부',
      affiliationEn: 'Dept. of Mechanical Engineering, SNU',
      imageUrl: '',
      order: 1,
    },
    {
      id: '2',
      nameKo: '김철수',
      nameEn: 'Chulsoo Kim',
      role: 'mentor',
      titleKo: '박사과정 멘토',
      titleEn: 'PhD Mentor',
      affiliationKo: '서울대학교 기계공학부',
      affiliationEn: 'Dept. of Mechanical Engineering, SNU',
      imageUrl: '',
      order: 1,
    },
    {
      id: '3',
      nameKo: '이영희',
      nameEn: 'Younghee Lee',
      role: 'executive',
      titleKo: '동아리장',
      titleEn: 'Club President',
      affiliationKo: '서울대학교 전기정보공학부',
      affiliationEn: 'Dept. of Electrical and Computer Engineering, SNU',
      imageUrl: '',
      order: 1,
    },
    {
      id: '4',
      nameKo: '박민준',
      nameEn: 'Minjun Park',
      role: 'executive',
      titleKo: '부동아리장',
      titleEn: 'Vice President',
      affiliationKo: '서울대학교 컴퓨터공학부',
      affiliationEn: 'Dept. of Computer Science, SNU',
      imageUrl: '',
      order: 2,
    },
    {
      id: '5',
      nameKo: '최수진',
      nameEn: 'Sujin Choi',
      role: 'manipulation',
      titleKo: 'Manipulation 팀',
      titleEn: 'Manipulation Team',
      affiliationKo: '서울대학교 기계공학부',
      affiliationEn: 'Dept. of Mechanical Engineering, SNU',
      imageUrl: '',
      order: 1,
    },
    {
      id: '6',
      nameKo: '정우성',
      nameEn: 'Woosung Jung',
      role: 'navigation',
      titleKo: 'Navigation 팀',
      titleEn: 'Navigation Team',
      affiliationKo: '서울대학교 전기정보공학부',
      affiliationEn: 'Dept. of ECE, SNU',
      imageUrl: '',
      order: 1,
    },
    {
      id: '7',
      nameKo: '한지우',
      nameEn: 'Jiwoo Han',
      role: 'reasoning',
      titleKo: 'Reasoning 팀',
      titleEn: 'Reasoning Team',
      affiliationKo: '서울대학교 컴퓨터공학부',
      affiliationEn: 'Dept. of Computer Science, SNU',
      imageUrl: '',
      order: 1,
    },
    {
      id: '8',
      nameKo: '오세연',
      nameEn: 'Seyeon Oh',
      role: 'perception',
      titleKo: 'Perception 팀',
      titleEn: 'Perception Team',
      affiliationKo: '서울대학교 전기정보공학부',
      affiliationEn: 'Dept. of ECE, SNU',
      imageUrl: '',
      order: 1,
    },
    {
      id: '9',
      nameKo: '송태양',
      nameEn: 'Taeyang Song',
      role: 'alumni',
      titleKo: '졸업생 (현 삼성전자)',
      titleEn: 'Alumni (Samsung Electronics)',
      affiliationKo: '삼성전자 로봇사업부',
      affiliationEn: 'Samsung Electronics, Robot Division',
      imageUrl: '',
      order: 1,
    },
  ],
};
